<div class="content">
    <div class="individual top">

    <div class="row justify">
        <div class="col col-6">
            <img src="img/modelo top edit.jpg" class="img-responsive" alt="image" width="100%" height="auto">
        </div>
        <div class="col col-6">
            <div class="row justify">
                <img src="img/top edit.jpg" class="img-responsive" alt="image" width="100%" height="auto">
            </div>
            <div class="row justify description">
                <h1>
                    Top Deportivo 
                </h1>
                <h1>
                    ADIDAS
                </h1>
                <h3>
                    Talle S
                </h3>
                <h3>
                    $350
                </h3>
            </div>
        </div>
    </div>
    <div class="individual remera">

    <div class="row justify">
        
        <div class="col col-6">
            <div class="row justify">
                <img src="img/remera.png" class="img-responsive" alt="image" width="100%" height="auto">
            </div>
            <div class="row justify description">
                <h1>
                    Chomba 
                </h1>
                <h1>
                    ADIDAS
                </h1>
                <h3>
                    Talle S
                </h3>
                <h3>
                    $300
                </h3>
            </div>
        </div>
        <div class="col col-6">
            <img src="public\img\ modelo remera edit.png" class="img-responsive" alt="image" width="100%" height="auto">
        </div>
    </div>
</div>