<div class="titlebox" height="100%">
    <h1 class="info">INFO<h1>

<div class="itembox">
    <h1 class="item">No tenemos showroom ni hacemos envios por el momento</h1>
    <h1 class="item">Las prendas se reservan solo si se cordina fecha y lugar de encuetro para la entrega</h1>
    <h1 class="item">Podes pagar en efectivo, o con mercado pago con un 10% de recargo</h1>
    <h1 class="item">Entrega gratuita en Ramos Mejia, en otro punto al precio de la prenda se le suma un viatico</h1>

</div>
</div>