<div class="row justify">
    <div class="oneback col col-6">
        <img src="img/modelo top edit.png" class="front img-responsive" alt="image" width="auto" height="100%">
        <img src="img/modelo top 2.png" class="back img-responsive" alt="image" width="auto" height="100%">
    </div>
    <div class="col col-6">
        <div class="row justify">
            <img src="img/top edit.jpg" class="img-responsive" alt="image" width="100%" height="auto">
        </div>
        <div class="row justify description">
            <h1>
                <?php echo $name; ?> 
            </h1>
            <h1>
                <?php echo $marca; ?> 
            </h1>
            <h3>
                <?php echo $size; ?>
            </h3>
            <h3>
                <?php echo '$'.$price; ?>
            </h3>
        </div>
    </div>
</div>